server:
  port: 8080

spring:
  application:
    name: edge
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

