server:
  port: 8889

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hahopp/jordy-tube-config.git

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"